name: riverpod_files
description: 'A new Flutter project.'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1

  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  http: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.6.5

  
  freezed: ^3.1.0
  json_serializable: ^6.9.5
flutter:
  uses-material-design: true
  assets:
    - assets/products/
    - assets/coffee_shop/